### ISSUE TITLE
Installing disk-images created by packer-maas

### ISSUE THREAD

**Issue by ckleu** [deltaprojects/foreman_discovery_image_installer#3]
Would this tool be able to write [packet-maas](https://github.com/canonical/packer-maas) disk-images directly to bare-metal? The suggested OpenStack diskimage-creator does not seem to have the ability to install an ISO to a disk-image (uses cloud images).

Looking for a solution to generate disk-images from install ISOs (such as Red Hat) and the deploy that to bare-metal without running through the entire kickstart.ks script.
Ubuntu MAAS (disk-images) takes about 5min for a deploy, where cobbler (PXE boot) takes 15min to 30min to have the node ready for use.

**Comment by Raboo** [comment]
Hmm, I haven't tried it but I'm pretty sure OpenStack diskimage-builder can create CentOS images. 
And documentation seem to have instructions om how to create images for Red Hat, https://docs.openstack.org/diskimage-builder/latest/elements/rhel/README.html.
Also Red Hat seem to have something called livemedia-creator, which seem to be able to create images for Red Hat

I am not so familiar with MAAS. But if it is able to have a custom pxe during install, it should be able to run this project.

@ananace You have previously used this project with CentOS, have you used it with Red Hat?
Also, could you perhaps share any custom stuff or details about running this with CentOS images?

(Update: found details about Red Hat and diskmage-builder)

**Comment by ananace** [comment]
We only ever did CentOS deployments (a normal CentOS install, with the cloud-init packages, and then trimmed out to a deployable image), and even then only for testing. No idea how this would gel with regular RHEL and subscriptions/licenses.  
The only image deploys we ended up doing in production were all with Ubuntu derivates, since they lacked scriptable installers.

**Comment by ckleu** [comment]
It is just two separate workflows and requirements we have:
- some deployments are to create Ubuntu/CentOS nodes using LTS/released OS (more regular formats, want to deploy disk images to save time, format more regularly to ensure things are automated)
- test Red Hat QA images (usually provided as boot/DVD ISOs)

**Comment by ckleu** [comment]
One of our goals is to get closer to the Kernel development cycle and use Fedora/Debian for this purpose during daily tests.. 

Can Foreman deploy both disk-images and execute ISO-based installs? Currently, our environments with these two requirements are split (cobbler for ISO, MAAS for disk-images)

**Comment by Raboo** [comment]
[Foreman](https://theforeman.org/) usually boots deployments/installs over PXE. So you can boot an ISO. But a more common practice I believe is that extract parts that is need just for netboot. Ubuntu and most distros has some specific netboot stuff(initrd, vmlinuz, minimal archive for install packages only) that you download and host locally (you could do it directly over Internet, but would be slow and wasting bandwidth). And with Ubuntu/Debian you use something called Preseed for doing a "silent" full installation like when installing from the ISO. The process is quite similar for RHEL/CentOS, but there you use kickstart.

[Foreman](https://theforeman.org/) does do this as standard operation. However with this poorly named project foreman_discovery_image_installer you can boot images instead and skip the entire Preseed/Kickstart parts and just use cloud-init as the final configuration step. So yes, you can use Foreman for both ISO-based/traditional installs and image installs.

And with MAAS if you can have a custom PXE for the deployment part. Then this project should work with MAAS.
And in my previous post I linked to the diskimage-builder article which describes how to create images for RHEL(however I believe I use RAW images for Ubuntu, not qcow2).

With that said, I currently don't have time to test this with MAAS, but I am happy to answer any questions you get along the way. And if you do get this to work with MAAS, I would love a PR with some documentation on how to use foreman_discovery_image_installer with MAAS.

(I really should figure out a better name for this project, maybe PXE Linux image installer.)

**Comment by Raboo** [comment]
Closing this issue, I can reopen if you have anything more to add.
If you do get this setup with MAAS. I would love a PR with documentation on how to do so.
